app:
  redis:
    enabled: false
    conn: 127.0.0.1:6379
    dbNum: 8
    password: 123456
    timeout: 3000
    sentinel:
      enabled: false
      master: bookMaster
      nodes: 127.0.0.1:16379,127.0.0.1:26379,127.0.0.1:36379