// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/oauth/oauth.proto

package io_github_entere_srv_oauth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Oauth service

type OauthService interface {
	LoginByPassword(ctx context.Context, in *LoginRequest, opts ...client.CallOption) (*LoginResponse, error)
}

type oauthService struct {
	c    client.Client
	name string
}

func NewOauthService(name string, c client.Client) OauthService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "io.github.entere.srv.oauth"
	}
	return &oauthService{
		c:    c,
		name: name,
	}
}

func (c *oauthService) LoginByPassword(ctx context.Context, in *LoginRequest, opts ...client.CallOption) (*LoginResponse, error) {
	req := c.c.NewRequest(c.name, "Oauth.LoginByPassword", in)
	out := new(LoginResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Oauth service

type OauthHandler interface {
	LoginByPassword(context.Context, *LoginRequest, *LoginResponse) error
}

func RegisterOauthHandler(s server.Server, hdlr OauthHandler, opts ...server.HandlerOption) error {
	type oauth interface {
		LoginByPassword(ctx context.Context, in *LoginRequest, out *LoginResponse) error
	}
	type Oauth struct {
		oauth
	}
	h := &oauthHandler{hdlr}
	return s.Handle(s.NewHandler(&Oauth{h}, opts...))
}

type oauthHandler struct {
	OauthHandler
}

func (h *oauthHandler) LoginByPassword(ctx context.Context, in *LoginRequest, out *LoginResponse) error {
	return h.OauthHandler.LoginByPassword(ctx, in, out)
}
