// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/user.proto

package io_github_entere_srv_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserData struct {
	UserID               uint64   `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserData) Reset()         { *m = UserData{} }
func (m *UserData) String() string { return proto.CompactTextString(m) }
func (*UserData) ProtoMessage()    {}
func (*UserData) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{0}
}

func (m *UserData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserData.Unmarshal(m, b)
}
func (m *UserData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserData.Marshal(b, m, deterministic)
}
func (m *UserData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserData.Merge(m, src)
}
func (m *UserData) XXX_Size() int {
	return xxx_messageInfo_UserData.Size(m)
}
func (m *UserData) XXX_DiscardUnknown() {
	xxx_messageInfo_UserData.DiscardUnknown(m)
}

var xxx_messageInfo_UserData proto.InternalMessageInfo

func (m *UserData) GetUserID() uint64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *UserData) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{1}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type QueryUserRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryUserRequest) Reset()         { *m = QueryUserRequest{} }
func (m *QueryUserRequest) String() string { return proto.CompactTextString(m) }
func (*QueryUserRequest) ProtoMessage()    {}
func (*QueryUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{2}
}

func (m *QueryUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryUserRequest.Unmarshal(m, b)
}
func (m *QueryUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryUserRequest.Marshal(b, m, deterministic)
}
func (m *QueryUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryUserRequest.Merge(m, src)
}
func (m *QueryUserRequest) XXX_Size() int {
	return xxx_messageInfo_QueryUserRequest.Size(m)
}
func (m *QueryUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryUserRequest proto.InternalMessageInfo

func (m *QueryUserRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *QueryUserRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

type QueryUserResponse struct {
	Error                *Error    `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Data                 *UserData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *QueryUserResponse) Reset()         { *m = QueryUserResponse{} }
func (m *QueryUserResponse) String() string { return proto.CompactTextString(m) }
func (*QueryUserResponse) ProtoMessage()    {}
func (*QueryUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{3}
}

func (m *QueryUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryUserResponse.Unmarshal(m, b)
}
func (m *QueryUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryUserResponse.Marshal(b, m, deterministic)
}
func (m *QueryUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryUserResponse.Merge(m, src)
}
func (m *QueryUserResponse) XXX_Size() int {
	return xxx_messageInfo_QueryUserResponse.Size(m)
}
func (m *QueryUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryUserResponse proto.InternalMessageInfo

func (m *QueryUserResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *QueryUserResponse) GetData() *UserData {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*UserData)(nil), "io.github.entere.srv.user.UserData")
	proto.RegisterType((*Error)(nil), "io.github.entere.srv.user.Error")
	proto.RegisterType((*QueryUserRequest)(nil), "io.github.entere.srv.user.QueryUserRequest")
	proto.RegisterType((*QueryUserResponse)(nil), "io.github.entere.srv.user.QueryUserResponse")
}

func init() { proto.RegisterFile("proto/user/user.proto", fileDescriptor_9b283a848145d6b7) }

var fileDescriptor_9b283a848145d6b7 = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x2d, 0x4e, 0x2d, 0x02, 0x13, 0x7a, 0x60, 0xbe, 0x90, 0x64, 0x66, 0xbe, 0x5e,
	0x7a, 0x66, 0x49, 0x46, 0x69, 0x92, 0x5e, 0x6a, 0x5e, 0x49, 0x6a, 0x51, 0xaa, 0x5e, 0x71, 0x51,
	0x99, 0x1e, 0x48, 0x81, 0x92, 0x1d, 0x17, 0x47, 0x68, 0x71, 0x6a, 0x91, 0x4b, 0x62, 0x49, 0xa2,
	0x90, 0x18, 0x17, 0x1b, 0x48, 0xcc, 0xd3, 0x45, 0x82, 0x51, 0x81, 0x51, 0x83, 0x25, 0x08, 0xca,
	0x13, 0x92, 0xe2, 0xe2, 0x00, 0xb1, 0xfc, 0x12, 0x73, 0x53, 0x25, 0x98, 0x14, 0x18, 0x35, 0x38,
	0x83, 0xe0, 0x7c, 0x25, 0x5d, 0x2e, 0x56, 0xd7, 0xa2, 0xa2, 0xfc, 0x22, 0x21, 0x21, 0x2e, 0x96,
	0xe4, 0xfc, 0x94, 0x54, 0xb0, 0x56, 0xd6, 0x20, 0x30, 0x5b, 0x48, 0x80, 0x8b, 0x39, 0xb7, 0x38,
	0x1d, 0xaa, 0x07, 0xc4, 0x54, 0x72, 0xe3, 0x12, 0x08, 0x2c, 0x4d, 0x2d, 0xaa, 0x04, 0xd9, 0x19,
	0x94, 0x5a, 0x58, 0x9a, 0x5a, 0x5c, 0x82, 0x66, 0x2d, 0x27, 0x51, 0xd6, 0xb6, 0x30, 0x72, 0x09,
	0x22, 0x19, 0x54, 0x5c, 0x90, 0x9f, 0x57, 0x9c, 0x2a, 0x64, 0xc6, 0xc5, 0x9a, 0x0a, 0x72, 0x0c,
	0xd8, 0x20, 0x6e, 0x23, 0x05, 0x3d, 0x9c, 0xfe, 0xd6, 0x03, 0x3b, 0x3a, 0x08, 0xa2, 0x5c, 0xc8,
	0x9c, 0x8b, 0x25, 0x25, 0xb1, 0x24, 0x11, 0x6c, 0x0b, 0xb7, 0x91, 0x32, 0x1e, 0x6d, 0xb0, 0xb0,
	0x0a, 0x02, 0x6b, 0x30, 0x7a, 0xc2, 0xc8, 0xc5, 0x02, 0x12, 0x12, 0xca, 0xe3, 0xe2, 0x87, 0x3b,
	0xc7, 0xa9, 0x12, 0xe4, 0x44, 0x21, 0x6d, 0x3c, 0xc6, 0xa0, 0x87, 0x81, 0x94, 0x0e, 0x71, 0x8a,
	0x21, 0xfe, 0x54, 0x62, 0x10, 0xca, 0xe1, 0xe2, 0x45, 0xb2, 0xcf, 0xd3, 0x85, 0xa6, 0xb6, 0x25,
	0xb1, 0x81, 0x93, 0x91, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x29, 0xf0, 0xb6, 0x50, 0x5f, 0x02,
	0x00, 0x00,
}
